name: Melon Ticket Discord Notifier

on:
  workflow_dispatch:       
  schedule:               
    - cron: '*/1 * * * *'  

jobs:
  check-melon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run melon seat checker
        run: node check-melon-seat.js
